prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/homepagelist.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/united_nations_png.sql
@@application/shared_components/files/styles_css.sql
@@application/shared_components/files/invoice_css.sql
@@application/shared_components/files/styles_min_css.sql
@@application/shared_components/files/invoice_min_css.sql
@@application/shared_components/files/apex_data_pkg_ph_complain_370426_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_notification_228997_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_expenses_824917_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_expired_medcine_33387_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_shortcomings_27811_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_user_activity_517363_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_income_45368_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_invoice_67496_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_medcine_85694_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_orders_225667_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_orders_medcine_30201_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_providers_783885_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_return_medcine_454347_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_setting_608825_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_unit_625102_zip.sql
@@application/shared_components/files/apex_data_pkg_ph_users_246733_zip.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/user_activity_login.sql
@@application/shared_components/logic/application_processes/quantitychange.sql
@@application/shared_components/logic/application_processes/dateexpired.sql
@@application/shared_components/logic/application_processes/user_activity_logout.sql
@@application/shared_components/logic/application_processes/getnotify.sql
@@application/shared_components/logic/application_items/complain_num.sql
@@application/shared_components/logic/application_items/ex_date_num.sql
@@application/shared_components/logic/application_items/lastmindate.sql
@@application/shared_components/logic/application_items/mindate.sql
@@application/shared_components/logic/application_items/minquantiti.sql
@@application/shared_components/logic/application_items/min_quantity_num.sql
@@application/shared_components/logic/application_items/notifycounter.sql
@@application/shared_components/logic/application_items/returned_duration.sql
@@application/shared_components/logic/application_computations/minquantiti.sql
@@application/shared_components/logic/application_computations/mindate.sql
@@application/shared_components/logic/application_computations/lastmindate.sql
@@application/shared_components/logic/application_computations/returned_duration.sql
@@application/shared_components/logic/application_computations/complain_num.sql
@@application/shared_components/logic/application_computations/ex_date_num.sql
@@application/shared_components/logic/application_computations/min_quantity_num.sql
@@application/shared_components/logic/application_computations/notifycounter.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/invoicetype.sql
@@application/shared_components/user_interface/lovs/medcine_name.sql
@@application/shared_components/user_interface/lovs/months.sql
@@application/shared_components/user_interface/lovs/ph_medcine_medcine_name.sql
@@application/shared_components/user_interface/lovs/ph_unit_unit_name.sql
@@application/shared_components/user_interface/lovs/providename.sql
@@application/shared_components/user_interface/lovs/providertype.sql
@@application/shared_components/user_interface/lovs/rolemenu.sql
@@application/shared_components/user_interface/lovs/username.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/page_copu.sql
@@application/shared_components/user_interface/templates/page/copy_of_standard_page.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/main_authentication_scheme.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00034.sql
@@application/pages/page_09999.sql
@@application/pages/page_10010.sql
@@application/pages/page_10011.sql
@@application/end_environment.sql
